In [175]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df=pd.read_csv("titanic.csv")
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [4]:
#ML Prediction based upon Pclass,Sex,Age,Fare
#Target Variable is Survived where 0=not survived and 1=survived

In [176]:
data=df.drop(['PassengerId','Name','SibSp','Parch','Ticket','Cabin','Embarked'],axis=1)
data

Survived  Pclass     Sex   Age     Fare
0           0       3    male  22.0   7.2500
1           1       1  female  38.0  71.2833
2           1       3  female  26.0   7.9250
3           1       1  female  35.0  53.1000
4           0       3    male  35.0   8.0500
..        ...     ...     ...   ...      ...
886         0       2    male  27.0  13.0000
887         1       1  female  19.0  30.0000
888         0       3  female   NaN  23.4500
889         1       1    male  26.0  30.0000
890         0       3    male  32.0   7.7500

[891 rows x 5 columns]

In [177]:
from sklearn.model_selection import train_test_split

In [178]:
#Nominal Data conversion
gender=pd.get_dummies(data.Sex).iloc[:,:1]
gender

female
0         0
1         1
2         1
3         1
4         0
..      ...
886       0
887       1
888       1
889       0
890       0

[891 rows x 1 columns]

In [179]:
data=pd.concat([data,gender],axis=1)
data

Survived  Pclass     Sex   Age     Fare  female
0           0       3    male  22.0   7.2500       0
1           1       1  female  38.0  71.2833       1
2           1       3  female  26.0   7.9250       1
3           1       1  female  35.0  53.1000       1
4           0       3    male  35.0   8.0500       0
..        ...     ...     ...   ...      ...     ...
886         0       2    male  27.0  13.0000       0
887         1       1  female  19.0  30.0000       1
888         0       3  female   NaN  23.4500       1
889         1       1    male  26.0  30.0000       0
890         0       3    male  32.0   7.7500       0

[891 rows x 6 columns]

In [180]:
new_data=data.drop(['Sex'],axis=1)
new_data

Survived  Pclass   Age     Fare  female
0           0       3  22.0   7.2500       0
1           1       1  38.0  71.2833       1
2           1       3  26.0   7.9250       1
3           1       1  35.0  53.1000       1
4           0       3  35.0   8.0500       0
..        ...     ...   ...      ...     ...
886         0       2  27.0  13.0000       0
887         1       1  19.0  30.0000       1
888         0       3   NaN  23.4500       1
889         1       1  26.0  30.0000       0
890         0       3  32.0   7.7500       0

[891 rows x 5 columns]

In [181]:
#Data imputation
new_data.isnull()
new_data.isnull().sum()

Survived      0
Pclass        0
Age         177
Fare          0
female        0
dtype: int64

In [182]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.impute import KNNImputer

In [183]:
#guessing n-neighborhood to be 2 to avoid straying valuation error
impute=KNNImputer(n_neighbors=2)
data1= impute.fit_transform(new_data)

In [184]:
ndata=pd.DataFrame(data1,columns=['Survived','Pclass','Age','Fare','female'])
ndata

Survived  Pclass   Age     Fare  female
0         0.0     3.0  22.0   7.2500     0.0
1         1.0     1.0  38.0  71.2833     1.0
2         1.0     3.0  26.0   7.9250     1.0
3         1.0     1.0  35.0  53.1000     1.0
4         0.0     3.0  35.0   8.0500     0.0
..        ...     ...   ...      ...     ...
886       0.0     2.0  27.0  13.0000     0.0
887       1.0     1.0  19.0  30.0000     1.0
888       0.0     3.0  20.0  23.4500     1.0
889       1.0     1.0  26.0  30.0000     0.0
890       0.0     3.0  32.0   7.7500     0.0

[891 rows x 5 columns]

In [159]:
from sklearn.preprocessing import LabelEncoder

In [185]:
nd1 = ndata.rename(columns={'female': 'Gender'})
nd1

Survived  Pclass   Age     Fare  Gender
0         0.0     3.0  22.0   7.2500     0.0
1         1.0     1.0  38.0  71.2833     1.0
2         1.0     3.0  26.0   7.9250     1.0
3         1.0     1.0  35.0  53.1000     1.0
4         0.0     3.0  35.0   8.0500     0.0
..        ...     ...   ...      ...     ...
886       0.0     2.0  27.0  13.0000     0.0
887       1.0     1.0  19.0  30.0000     1.0
888       0.0     3.0  20.0  23.4500     1.0
889       1.0     1.0  26.0  30.0000     0.0
890       0.0     3.0  32.0   7.7500     0.0

[891 rows x 5 columns]

In [198]:
#Defining
x=nd1[["Pclass","Age","Fare","Gender"]]
y=nd1["Survived"]

In [200]:
#Re-applying "fixed"-randomized 80:20 split model
x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=0.2,random_state=10)
nd1

Survived  Pclass   Age     Fare  Gender
0         0.0     3.0  22.0   7.2500     0.0
1         1.0     1.0  38.0  71.2833     1.0
2         1.0     3.0  26.0   7.9250     1.0
3         1.0     1.0  35.0  53.1000     1.0
4         0.0     3.0  35.0   8.0500     0.0
..        ...     ...   ...      ...     ...
886       0.0     2.0  27.0  13.0000     0.0
887       1.0     1.0  19.0  30.0000     1.0
888       0.0     3.0  20.0  23.4500     1.0
889       1.0     1.0  26.0  30.0000     0.0
890       0.0     3.0  32.0   7.7500     0.0

[891 rows x 5 columns]

In [193]:
from sklearn import tree

In [208]:
model=tree.DecisionTreeClassifier()
model.fit(x_test,y_test)

DecisionTreeClassifier()

In [209]:
model.score(x_test,y_test)

1.0

In [210]:
#Perfect Data expectation

In [250]:
#Chronology order = Passenger Class,Age,Fare,Gender (Male=0,Female=1)
Prediction=model.predict([[2,22,7.765,1]])
Prediction

array([1.])

In [ ]:
#array([1.])=Survived!
#array([0.])=Not survived!